In [6]:
# pip install numpy
# conda install numpy
#impor usado para instalas
#permite manejar listas arreglos y tuplas
import numpy as np

In [5]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array([1,2,3])))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [13]:
np.zeros(5)# 1 solo numero paun arregle
np.zeros([5,5]) # 1listao tuplapara una matriz de n dimensiones
np.zeros((5,5))# 1 matriz con tupla
#arreglode 6 dimensiones
np.zeros([1000,200])# se puede trabar con x no. de dimensiones
np.zeros((2,3,4,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [14]:
np.ones(7)
np.ones((1,2,3,4))

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [15]:
#diagonalcon unos y las demas con 0 matrizidentidad
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
np.arange(5)#devuelve arreglo desde el 0 hasta completar el #

array([0, 1, 2, 3, 4])

In [17]:
np.arange(4,20)#define un desde y hasta el ultimo abierto
#empiezame desde el 4 hasta el 20 pero el 20 esabierto-no toma

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(-12,1)# permite con negativos

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [20]:
#ejemplo queremos q salte de 2 en dos
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
np.arange(0,2,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [22]:
np.arange(10)# tenemos 1 dimension con 10 elementos

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
#cambiar # de dimesiones de un arrelo
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
np.arange(20).reshape(2,5,2) #le puse a 3 dimensiones

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [28]:
np.arange(20).reshape(2,5,2).reshape(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
len(np.ones(12))

12

In [31]:
len(np.ones(12).reshape(4,3))

4

In [32]:
# DE CUANTAS DIMENSIONES ES ESTE ARREGLO?
np.ones(12).reshape(4,3).shape

(4, 3)

In [33]:
#para acceder aun indice especifico
np.arange(12).reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [35]:
np.arange(12).reshape(6,2)[1,1]

3

In [36]:
a = np.array([10,10,10])#arreglo de 1 dimension con 3 elementos
b = np.array([5,5,5])

In [37]:
a + b # sUMA

array([15, 15, 15])

In [38]:
#RESTAa
a - b

array([5, 5, 5])

In [39]:
#Suma elvaloracadaelemento
a + 7 

array([17, 17, 17])

In [40]:
a + 4.4

array([14.4, 14.4, 14.4])

In [42]:
#multiplicacion
a * 3.3

array([33., 33., 33.])

In [43]:
#division
a / b

array([2., 2., 2.])

In [44]:
b / 3

array([1.66666667, 1.66666667, 1.66666667])

In [45]:
#usaar modulos
a % b

array([0, 0, 0], dtype=int32)

In [46]:
a % 3

array([1, 1, 1], dtype=int32)

In [47]:
muestra = np.arange(20).reshape(5,2,2)

In [48]:
muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [49]:
#quienes tienen mas de 5 en glucosa
respuesta_glucosa = muestra >5

In [50]:
respuesta_glucosa

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [51]:
muestra[respuesta_glucosa]# devuelve todos los valoresq 
                          #cumplanla condicion

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [68]:
#AHORA LOS MAYORES A 5Y MENOR 14 Y SOLO LOS PARES
mayores_cinco = muestra >5
menores_catorce = muestra < 14
pares = muestra % 2 == 0 
respuesta = mayores_cinco & menores_catorce & pares

In [69]:
muestra[respuesta]

array([ 6,  8, 10, 12])