In [1]:
import numpy as np

In [4]:
#arreglo de grados
arreglo_grados = np.array([0,30,45,60,90])
arreglo_grados

array([ 0, 30, 45, 60, 90])

In [6]:
arreglo_radianes = arreglo_grados * np.pi / 80
arreglo_radianes

array([0.        , 1.17809725, 1.76714587, 2.35619449, 3.53429174])

In [7]:
#funcion seno sin
np.sin(arreglo_radianes)

array([ 0.        ,  0.92387953,  0.98078528,  0.70710678, -0.38268343])

In [8]:
np.cos(arreglo_radianes)

array([ 1.        ,  0.38268343, -0.19509032, -0.70710678, -0.92387953])

In [9]:
np.tan(arreglo_radianes)

array([ 0.        ,  2.41421356, -5.02733949, -1.        ,  0.41421356])

In [14]:
#arreglorandomico
arreglo_random = np.random.randint(
11#quiero q me trigas un numero entero hasta el 11[0, 11[
)
arreglo_random

9

In [18]:
numero_random_negativo = np.random.randint(
-9, #randomicos enteros desde el -9 al 2 [-9, 2[
 2
)
numero_random_negativo

-8

In [19]:
#arreglo de valores
arreglo_random = np.random.randint(
    10,# arreglo del 10 al20 sacame 8 elementos
    20,
    8
)
arreglo_random

array([11, 18, 18, 17, 16, 12, 14, 10])

In [22]:
np.random.rand(9) #9 elementos
np.random.rand(3,2)#6 elementos (3*2 dimensiones)

array([[0.3636557 , 0.55583005],
       [0.92421528, 0.10873777],
       [0.99364491, 0.54487281]])

In [23]:
#PROMEDIO
np.average(arreglo_random)

14.5

In [24]:
np.mean(arreglo_random)

14.5

In [25]:
np.median(arreglo_random)#mediana

15.0

In [26]:
np.std(arreglo_random)#desviacion estandar

3.0

In [27]:
np.var(arreglo_random)#varianza

9.0

In [28]:
#otra forma de calcular la media
arreglo_random.mean()

14.5