In [2]:
import numpy as np

In [4]:
#elevar al cuadrado
arreglo = np.arange(11)**2
arreglo

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [5]:
# hacer secciones dentro de un arreglo
arreglo[0:7]

array([ 0,  1,  4,  9, 16, 25, 36], dtype=int32)

In [7]:
arreglo[-6:-1]

array([25, 36, 49, 64, 81], dtype=int32)

In [8]:
arreglo[:]

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [10]:
arreglo[2:-3]

array([ 4,  9, 16, 25, 36, 49], dtype=int32)

In [11]:
arreglo[2:]

array([  4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [13]:
arreglo[:-3]

array([ 0,  1,  4,  9, 16, 25, 36, 49], dtype=int32)

In [14]:
arreglo[0:6]

array([ 0,  1,  4,  9, 16, 25], dtype=int32)

In [17]:
arreglo[:]

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [18]:
arreglo[0:6:2]#saltos de2 en dos

array([ 0,  4, 16], dtype=int32)

In [20]:
arreglo[::2]

array([  0,   4,  16,  36,  64, 100], dtype=int32)

In [21]:
arreglo[::-2]

array([100,  64,  36,  16,   4,   0], dtype=int32)