In [1]:
# EXAMEN I BIMESTRE

In [2]:
import numpy as np
import pandas as pd
from scipy import misc
import matplotlib.pyplot as plt

In [34]:
#1)Crear un vector de ceros de tamaño 10
vector = np.zeros(10)
vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
# 2) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1
vector = np.zeros(10)
vector[5] = 1
vector

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [33]:
# 3) Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.
vector = np.arange(50)
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [6]:
# 4) Crear una matriz de 3 x 3 con valores del cero al 8
matriz = np.arange(0,9,1).reshape(3,3)
matriz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# 5) Encontrar los indices que no sean cero en un arreglo
arreglo = [1,2,0,0,4,0]
nc_arreglo = np.array(arreglo)
np.where(nc_arreglo != 0)

(array([0, 1, 4], dtype=int64),)

In [8]:
# 6) Crear una matriz de identidad 3 x 3
matriz = np.eye(3)
matriz

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
# 7) Crear una matriz 3 x 3 x 3 con valores randomicos
matriz_3_3_3 = np.random.rand(3,3,3)
matriz_3_3_3

array([[[0.2849024 , 0.54290743, 0.64763672],
        [0.25332775, 0.14027599, 0.53727737],
        [0.69774083, 0.63782764, 0.26054166]],

       [[0.62193437, 0.65791145, 0.94520681],
        [0.64440904, 0.94025538, 0.61157626],
        [0.6130202 , 0.54643545, 0.93730611]],

       [[0.47899266, 0.33087852, 0.17431687],
        [0.73870519, 0.63539858, 0.64557823],
        [0.34874051, 0.91212498, 0.38763824]]])

In [37]:
# 8) Crear una matriz 10 x 10 y encontrar el mayor y el menor
matriz = np.arange(50, 100, 0.5).reshape(10,10)
print(matriz)
print(np.min(matriz)) 
print(np.max(matriz))

[[50.  50.5 51.  51.5 52.  52.5 53.  53.5 54.  54.5]
 [55.  55.5 56.  56.5 57.  57.5 58.  58.5 59.  59.5]
 [60.  60.5 61.  61.5 62.  62.5 63.  63.5 64.  64.5]
 [65.  65.5 66.  66.5 67.  67.5 68.  68.5 69.  69.5]
 [70.  70.5 71.  71.5 72.  72.5 73.  73.5 74.  74.5]
 [75.  75.5 76.  76.5 77.  77.5 78.  78.5 79.  79.5]
 [80.  80.5 81.  81.5 82.  82.5 83.  83.5 84.  84.5]
 [85.  85.5 86.  86.5 87.  87.5 88.  88.5 89.  89.5]
 [90.  90.5 91.  91.5 92.  92.5 93.  93.5 94.  94.5]
 [95.  95.5 96.  96.5 97.  97.5 98.  98.5 99.  99.5]]
50.0
99.5


In [30]:
#9) Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)
import numpy as np
from PIL import Image
img = Image.open('lena.png')
arr = np.array(img) # 640x480x4 array
arr[20, 30] # 4-vector, just like above

FileNotFoundError: [Errno 2] No such file or directory: 'lena.png'

In [13]:
# 10) ¿Como crear una serie de una lista, diccionario o arreglo?
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

series_lista = pd.Series(mylist)
print(series_lista)
series_arreglo = pd.Series(myarr)
print(series_arreglo)
series_dicionario = pd.Series(mydict)
print(series_dicionario)

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


In [14]:
# 11) ¿Como convertir el indice de una serie en una columna de un DataFrame?
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 
# Transformar la serie en dataframe y hacer una columna indice
df = pd.DataFrame(ser).reset_index().set_index(myarr)
df

index   0
0      a   0
1      b   1
2      c   2
3      e   3
4      d   4
5      f   5
6      g   6
7      h   7
8      i   8
9      j   9
10     k  10
11     l  11
12     m  12
13     n  13
14     o  14
15     p  15
16     q  16
17     r  17
18     s  18
19     t  19
20     u  20
21     v  21
22     w  22
23     x  23
24     y  24
25     z  25

In [15]:
# 12) ¿Como combinar varias series para hacer un DataFrame?
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

df1 = pd.DataFrame(ser1)
df1[1] = ser2
df1

df2 = pd.DataFrame(dict(serie1=ser1, serie2=ser2))
df2

serie1  serie2
0       a       0
1       b       1
2       c       2
3       e       3
4       d       4
5       f       5
6       g       6
7       h       7
8       i       8
9       j       9
10      k      10
11      l      11
12      m      12
13      n      13
14      o      14
15      p      15
16      q      16
17      r      17
18      s      18
19      t      19
20      u      20
21      v      21
22      w      22
23      x      23
24      y      24
25      z      25

In [16]:
# 13)  ¿Como obtener los items que esten en una serie A y no en una serie B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
resp = set(ser1) - set(ser2)
resp

{1, 2, 3}

In [17]:
#14) ¿Como obtener los items que no son comunes en una serie A y serie B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
resp = ser1.append(ser2).drop_duplicates(keep=False)
resp

0    1
1    2
2    3
2    6
3    7
4    8
dtype: int64

In [18]:
# 15) ¿Como obtener el numero de veces que se repite un valor en una serie?
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
valor_repetido = pd.Series.value_counts(ser)
valor_repetido

e    6
g    6
b    4
a    3
h    3
c    3
d    3
f    2
dtype: int64

In [19]:
# 16) ¿Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

In [22]:
#17) ¿Como transformar una serie de un arreglo de numpy a un DataFrame con un shape definido?
ser = pd.Series(np.random.randint(1, 10, 35))
#shape(7,5)
serie = ser.values.reshape(7, 5)
df = pd.DataFrame(serie)
df

0  1  2  3  4
0  1  1  8  7  8
1  9  3  5  3  4
2  5  5  2  1  6
3  3  1  8  9  4
4  9  9  7  1  2
5  3  6  6  8  4
6  5  5  9  5  5

In [23]:
#18) ¿Obtener los valores de una serie conociendo la posicion por indice?
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u
ser[pos]

0     a
4     e
8     i
14    o
20    u
dtype: object

In [24]:
# 19) ¿Como anadir series vertical u horizontalmente a un DataFrame?
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
df1 = pd.DataFrame(ser1)
df1[1] = ser2
df1

df2 = pd.DataFrame(ser1)
df2 = pd.concat([df2,ser2],axis=0)
df2

0
0  0
1  1
2  2
3  3
4  4
0  a
1  b
2  c
3  d
4  e

In [25]:
# 20) ¿Obtener la media de una serie agrupada por otra serie?
#groupby tambien esta disponible en series.

frutas = pd.Series(np.random.choice(['manzana', 'banana', 'zanahoria'], 10))
pesos = pd.Series(np.linspace(1, 10, 10))
print(pesos.tolist())
print(frutas.tolist())
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']

# Los valores van a cambiar por ser random
# apple     6.0
# banana    4.0
# carrot    5.8
# dtype: float64

series_agrupada = pd.DataFrame({"frutas": frutas, "pesos": pesos})
series_agrupada.groupby(['frutas']).mean()

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['manzana', 'banana', 'banana', 'zanahoria', 'manzana', 'zanahoria', 'banana', 'banana', 'zanahoria', 'banana']


pesos
frutas             
banana     6.000000
manzana    3.000000
zanahoria  6.333333

In [27]:
# 21) ¿Como importar solo columnas especificas de un archivo csv?
#https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv.
url = 'https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'
df=pd.read_csv(url,usecols = ['indus','medv'])
df

indus  medv
0     2.31  24.0
1     7.07  21.6
2     7.07  34.7
3     2.18  33.4
4     2.18  36.2
..     ...   ...
501  11.93  22.4
502  11.93  20.6
503  11.93  23.9
504  11.93  22.0
505  11.93  11.9

[506 rows x 2 columns]